# Generated by Django 4.2.1 on 2023-05-08 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_rename_users_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
