# Generated by Django 4.2.1 on 2023-05-10 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_remove_products_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('password', models.CharField(max_length=280)),
                ('email', models.EmailField(max_length=50)),
            ],
        ),
    ]
